apiVersion: batch/v1
kind: Job
metadata:
  name: my-perl-job-{{ .Release.Name }}
spec:
  template:
    spec:
      containers:
      - name: perl-container
        image: perl:{{ .Values.perl_version }}
        command: ["perl",  "-Mbignum=bpi", "-wle", "print 'Hello World!\n'"]
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 60
